name = "KnetOnnx"
uuid = "5598a57d-f0b8-44c7-a305-14fa4de76fa0"
authors = ["Ege  <egeersu@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
